Swap to zplug, cleanup a bit

diff --git a/.config/zsh/zshrc b/.config/zsh/zshrc
--- a/.config/zsh/zshrc
+++ b/.config/zsh/zshrc
@@ -6,6 +6,7 @@ umask 022
 if [[ ${TERM} == 'dumb' ]]; then
     return
 fi
+[[ $- =~ i ]] || return
 
 # Use emacs keybindings even if our EDITOR is set to vi
 bindkey -e
@@ -27,32 +28,67 @@ source-with-force ~/.zsh/secrets
 
 # zplug
 : ${ZPLUG_HOME:=$XDG_CACHE_HOME/zplug}
-: ${ZPLUG_DIR:=$XDG_CACHE_HOME/zplug/repos/zplug/zplug}
-: ${ZPLUG_REPOS:=$XDG_CACHE_HOME/zplug/repos}
+: ${ZPLUG_CACHE_FILE:=$ZPLUG_HOME/.cache}
+: ${ZPLUG_REPOS:=$ZPLUG_HOME/repos}
 : ${ZPLUG_CLONE_DEPTH:=1}
 
-if [[ ! -d $ZPLUG_DIR ]]; then
-    echo "- No zplug found in \$path or ZPLUG_HOME=$ZPLUG_HOME" >&2
+# Reset zplugs
+zplugs=()
 
-    echo "- Cloning zplug into ZPLUG_HOME=$ZPLUG_HOME" >&2
-    if ! git clone ${ZPLUG_REPO:-https://github.com/akatrevorjay/zplug.git} $ZPLUG_HOME/repos/zplug/zplug; then
+: ${ZPLUG_DIR:=$ZPLUG_REPOS/zplug/zplug}
+: ${ZPLUG_REPO:=https://github.com/akatrevorjay/zplug.git}
+
+if [[ ! -d $ZPLUG_DIR ]]; then
+    echo "- No zplug found in ZPLUG_DIR=$ZPLUG_DIR" >&2
+
+    echo "- Cloning zplug into ZPLUG_DIR=$ZPLUG_DIR" >&2
+    if ! git clone $ZPLUG_REPO $ZPLUG_DIR; then
         echo "- Failed." >&2
         return 1
     fi
 fi
+
 source $ZPLUG_DIR/init.zsh || return 1
 
-# TODO check plugins difference on hook and auto-load
-source-with-force ${^ZDOTDIRS}/zshplugins(-.)
+function zplug() {
+    # Replace self. Lazy loading.
+    unfunction zplug
+    autoload -Uz zplug
 
-if ! zplug check --verbose; then
-	printf "-- Found changes in zshplugins. Install them? [y/N]: "
-    if read -q; then
-        echo; zplug install
+    # TODO check plugins difference on hook and auto-load
+    source-with-force ${^ZDOTDIRS}/zshplugins(-.)
+}
+
+function zplugins-cache-is-clean() {
+    if [ ! -f $ZPLUG_CACHE_FILE ]; then
+        echo "- Cache file not found: $ZPLUG_CACHE_FILE" >&2
+        return 1
     fi
-fi
 
-zplug load --verbose
+    local plugins_file
+    for plugins_file in ${^ZDOTDIRS}/zshplugins(-.); do
+        if [ $plugins_file -nt $ZPLUG_CACHE_FILE ]; then
+            echo "- Detected change in $plugins_file" >&2
+            return 100
+        fi
+    done
+}
+
+if zplugins-cache-is-clean; then
+    echo "- Loading cache"
+    source $ZPLUG_CACHE_FILE
+else
+    echo "- Creating cache"
+
+    if ! zplug check --verbose; then
+	    printf "-- Found changes in zshplugins. Install them? [y/N]: "
+        if read -q; then
+            echo; zplug install
+        fi
+    fi
+
+    zplug load --verbose
+fi
 
 # Set up the prompt
 case "$USERNAME" in
